version: "3.7"

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      restart:
        always
    volumes:
    - ~/data/volumes/mysql:/etc/mysql
  redis:
    image: redis
    ports:
    - 6379:6379
    volumes:
    - ~/data/volumes/redis:/data
  api:
    build: .
    ports:
    - 8000:8000
    depends_on:
      - db


